/**
 * 功能模块统一导出
 */
export { registerPageLock } from './pageLock'
export { registerTableOfContents } from './tableOfContents'
export { registerImageCompressor } from './imageCompressor'
export { registerDocNavigation } from './docNavigation'
export { registerShortcut, addCustomShortcut, addCustomShortcuts, getShortcutManager, type ShortcutInfo } from './shortcut'
export { registerWordQuery } from './wordQuery'
export { registerGeneralSettings } from './generalSettings'
export { registerQRCode } from './qrCode'
export { registerUnitConverter } from './unitConverter'
export { registerSuperPanel } from './superPanel'
export { registerDiskBrowser } from './diskBrowser'
export { registerCodeImageGenerator } from './codeImageGenerator'
export { registerAIContentGenerator } from './aiContentGenerator'
export { registerStatistics } from './statistics'
export { registerPronunciation } from './pronunciation'
export { registerEncryption } from './encryption'
export { registerVideo } from './video'
export { registerEverythingSearch, showEverythingSearch, hideEverythingSearch, toggleEverythingSearch, everythingSearchVisible } from './everythingSearch'
export { registerSystemMonitor } from './systemMonitor'
export { registerApiReference, showApiReferencePanel } from './apiReference'
export { registerHighlight } from './highlight'
