// 统计模块常量（颜色/块类型标签/图片扩展名/零值）

import type { StatisticsData } from "./index"

export const NOTEBOOK_COLORS = [
  "#3b82f6",
  "#22c55e",
  "#f59e0b",
  "#ef4444",
  "#8b5cf6",
  "#06b6d4",
  "#ec4899",
  "#f97316",
  "#84cc16",
  "#14b8a6",
  "#6366f1",
  "#e11d48",
  "#0ea5e9",
  "#a855f7",
  "#10b981",
]

export const BLOCK_TYPE_LABELS: Record<string, string> = {
  d: "文档",
  p: "段落",
  h: "标题",
  l: "有序列表",
  i: "无序列表",
  c: "代码块",
  t: "表格",
  b: "引用块",
  html: "HTML块",
  query_embed: "嵌入查询",
  img: "图片",
  audio: "音频",
  video: "视频",
  widget: "挂件",
  iframe: "框架",
  super: "超级块",
  tag: "标签",
}

export const IMAGE_EXTENSIONS = [".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp"]

export const ZERO_STATISTICS: StatisticsData = {
  totalNotes: 0,
  totalWords: 0,
  totalBlocks: 0,
  totalAssets: 0,
  totalTags: 0,
  totalBacklinks: 0,
  todayCreated: 0,
  todayModified: 0,
  avgWordsPerDoc: 0,
  dailyStats: [],
  currentPeriod: "",
  periodTotalWords: 0,
  totalImages: 0,
  blockTypeStats: [],
  notebookCount: 0,
  codeBlocks: 0,
  writingStreak: 0,
  activeDays: 0,
}

/** 统计功能全量 i18n 默认文案（props.i18n 缺失时的兜底） */
export const STATS_DEFAULT_LABELS: Record<string, string> = {
  loading: "加载中...",
  refresh: "刷新",
  lastUpdate: "最后更新",
  wordsUnit: "字",
  notesUnit: "笔记",
  overview: "总览",
  totalNotes: "笔记总数",
  totalWords: "总字数",
  totalBlocks: "内容块",
  totalAssets: "附件",
  totalImages: "图片",
  totalTags: "标签",
  totalBacklinks: "双链",
  todayCreated: "今日新增",
  todayModified: "今日修改",
  avgWordsPerDoc: "平均字数",
  moreStats: "详细统计",
  tabOverview: "概览",
  activityHeatmap: "活跃热力图",
  notebookActivity: "写作活跃度",
  trendTab: "趋势",
  notebookDistributionTab: "笔记分布",
  reportTab: "报告",
  milestones: "里程碑",
  day: "日",
  week: "周",
  month: "月",
  year: "年",
  avgLabel: "日均字数",
  totalLabel: "总字数",
  days7: "7天",
  days15: "15天",
  days30: "30天",
  quarter: "季度",
  halfYear: "半年",
  fullYear: "整年",
  last1Year: "最近一年",
  last2Years: "最近两年",
  last3Years: "最近三年",
  title: "趋势分析",
  avgDailyCreated: "日均新增",
  avgDailyModified: "日均修改",
  historicalData: "历史数据",
  date: "日期",
  notes: "笔记",
  words: "字数",
  created: "新增",
  modified: "修改",
  change: "变化",
  blocks: "块",
  assets: "附件",
  dayOverDay: "日环比",
  weekOverWeek: "周环比",
  monthOverMonth: "月环比",
  docBarChartTitle: "各笔记本文档数",
  docChanges: "文档变化",
  noDocChanges: "当天无新增或修改",
  todayDeleted: "今日删除",
  noRecentDocs: "暂无最近更新的文档",
  recentUpdatedDocs: "最近更新",
  today: "今天",
  days3: "近3天",
  oneMonth: "近1月",
  wordRanking: "字数排行",
  emptyText: "暂无数据",
  blockTypeStats: "块类型分布",
  notebookWordPie: "笔记本字数占比",
  notebookBlockTypeTitle: "各笔记本块类型分布",
  reportTitle: "年度/月度报告",
  predictionTitle: "趋势预测",
  docsUnit: "篇",
  less: "少",
  more: "多",
  last30Days: "近30天",
  activeDaysCount: "天活跃",
  activeDaysLabel: "活跃天数",
  currentStreak: "当前连续",
  longestStreak: "最长连续",
  totalOperations: "总操作次数",
  months3: "3个月",
  months6: "6个月",
  year1: "1年",
  weekdayDistribution: "星期分布",
  monday: "周一",
  tuesday: "周二",
  wednesday: "周三",
  thursday: "周四",
  friday: "周五",
  saturday: "周六",
  sunday: "周日",
  mon: "一",
  wed: "三",
  fri: "五",
  metricDocsModified: "修改文档",
  metricDocsCreated: "新增文档",
  metricBlockEdits: "编辑块",
  allNotebooks: "全部笔记本",
  noData: "暂无数据",
  activeNotebooks: "活跃笔记本",
  mostActive: "最活跃",
  periodTotalWords: "期间总字数",
  dailyAvgWords: "日均字数",
  notebookRanking: "笔记本排行",
  notebookName: "笔记本",
  dailyAvg: "日均",
  proportion: "占比",
  days60: "60天",
  days90: "90天",
  days180: "180天",
  showAllMilestones: "显示全部 {count} 个里程碑",
  nextGoal: "下一目标",
  encourageAlmost: "只差一点点，加油！",
  encourageHalfway: "已完成过半，继续努力！",
  encourageStart: "千里之行，始于足下",
  tierCommon: "普通",
  tierRare: "稀有",
  tierEpic: "史诗",
  tierLegendary: "传说",
  catWriting: "写作达人",
  catKnowledge: "知识管理",
  catRich: "内容丰富",
}
