import type { DocStats } from "../types/index"

export const DEFAULT_DOC_STATS: DocStats = {
  totalDocs: 0,
  zeroByteDocs: 0,
  smallDocs: 0,
  mediumDocs: 0,
  largeDocs: 0,
  xlargeDocs: 0,
  duplicateNameGroups: 0,
  duplicateNameDocs: 0,
  updatedIn7Days: 0,
  updatedIn30Days: 0,
  updatedIn1To2Months: 0,
  updatedIn2To3Months: 0,
  updatedOverHalfYear: 0,
  deepDocs: 0,
  refDocs: 0,
  totalRefs: 0,
  imageDocs: 0,
  totalImages: 0,
  bookmarkedDocs: 0,
  noBookmarkDocs: 0,
  pendingPublishDocs: 0,
  publishedDocs: 0,
  unusedDocs: 0,
  noneBookmarkDocs: 0,
  fullPublishDocs: 0,
  partialPublishDocs: 0,
  noPublishDocs: 0,
  taggedDocs: 0,
  aliasedDocs: 0,
  memoedDocs: 0,
  incomingRefDocs: 0,
  orphanDocs: 0,
  platformCounts: {},
  wordCountDistribution: [],
  customBookmarkTop: [],
  distinctIssueCount: 0,
}
